name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
          plugin_achievements: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

